DROP TABLE IF EXISTS free_term CASCADE;
DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS clinic_user CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS clinic_user_role CASCADE;

